### ISSUE TITLE
strip-accents (Java version) misses some characters

### ISSUE THREAD

**Issue by jwr** [expez/superstring#5]
```
(string/strip-accents "ąćęółńśźż")
"aceołnszz"
```
Expected result is "aceolnszz". The character "ł" is U+0142, LATIN SMALL LETTER L WITH STROKE.

I tried reading about `InCombiningDiacriticalMarks` and now my head is spinning. I have no idea why 'ł' isn't caught by this regexp, but after doing said reading, I think the ClojureScript approach is a better and more practical one, also on the JVM side. I see that the ClojureScript string includes all the characters that I tested.

**Comment by expez** [comment]
The technical term is *diacritical mark*, but colloquially we mostly refer to these marks as *accents*.  The role of a diacritical mark is to change how a letter is pronounced, e.g. in the word naïve.

The latin letter isn't affected because it doesn't have a diacritical mark, this is just how that letter looks in that alphabet.

In other words, the clojure version works as expected, but the clojurescript version is wrong.  I copied the translations from [underscore.string](https://github.com/epeli/underscore.string/blob/master/cleanDiacritics.js), but I'm starting to think they're confused about what this function should do.  I remember removing the letter `æ` from their translation list, which is a ligature (in Norwegian this letter is the combination of `a` and `e`) without any diacritical marks.  I think what they're trying to do is `latinize`, but if that's their goal then their translation map needs to be [much larger](https://github.com/jprichardson/string.js/blob/master/lib/string.js#L13).

I'm going to fix the clojurescript version, but I consider the clojure version to be correct.  Since this isn't going in the direction you were hoping, what is the problem you're trying to solve?  Perhaps another function is missing from superstring.  A common reason for cleaning up text is for use in an URL.  The function [slug](http://expez.github.io/superstring/doc/superstring.core.html#var-slug) is intended for this purpose.

**Comment by jwr** [comment]
You are technically right, of course. But this is not what you Polish users will expect.

My reason for diving into this is `slug` — I need a way to convert blog post titles into URLs. And since a large part of my blog post titles are in Polish, I need to translate "ąćęółńśźż" into "aceolnszz". `slug` uses `strip-accents` internally, so this his how I ended up with `strip-accents`.

I realize this is a potential black hole, but the distinction you mentioned is moot in Polish. You either use Polish characters, or you convert them to latin lookalikes. This is what I expected from `slug` and you're right that I should probably have written about `slug` and not `strip-accents`.

**Comment by expez** [comment]
Is the `ł` the only character currently not handled that I need to fix to make my Polish users happy?  I think adding a translation table to `slug` to handle a few extra characters is perfectly fine.  Such a table will improve that function, as it now just removes any 'weird' characters to avoid percent encoding.

**Comment by jwr** [comment]
Yes, the example I posted in the initial report is complete — that's the entire list of characters that need to be handled in Polish. Only `ł` is not being handled.

Of course this is all a really minor issue, I could very well handle the translation myself, but I like superstring and I think it could be made slightly better.

**Comment by expez** [comment]
> I think it could be made slightly better.

I agree that this is an improvement and I appreciate the feedback!  I'll fix this later today and cut another release.

**Comment by expez** [comment]
`2.1.0` is now available on snapshot

**Comment by jwr** [comment]
Thanks, much appreciated.
